### ISSUE TITLE
MUST HAVES - before we can go live

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike.io#403]
- [ ] Adjust size of the EventBrite iFrame
- [ ] Change image **~Fuck~ Forget**
- [ ] Resizing the page, should not crop the picture
- [ ] The miniature (1x1) on _events_ page needs fixing

**An alternative** approach to fixing the latter two, could be to come up with an image, that's suitable for how the cropping and resizing works now. The Bob Marley image worked well, but was completely unrelated to the article - after we stopped mentioning "jamming".

We need an image that says _the same" as the content of the invite, but in a catchy way (remember, on SoMe, it's likely that the image is _all_ people will see.

The "Forget Wordpress, the Future is Here" image is perfect for the purpose, but if you stick to that, then we need to fix all the cropping and resizing, so it fits.

I trust you know what to do :-)

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/71955966-1c973000-31ea-11ea-9ccc-c6693066519e.png)

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/71956047-58ca9080-31ea-11ea-8895-50ecdc5a5604.png)

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/71956078-739d0500-31ea-11ea-8e2a-5f4724de556c.png)

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/71956229-e312f480-31ea-11ea-9944-533fb895b7a8.png)

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/71956426-6b919500-31eb-11ea-8100-1d2562291761.png)

**Comment by lakruzz** [comment]
@carolineolivia Jeg har lige opdateret description med nogle detaljer/options

**Comment by carolineolivia** [comment]
@lakruzz 
Jeg inddeler dem i flere issues, er det her så en epic?
